[package]
name = "flu-prelude"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "User-facing prelude for flu data pipelines"

[dependencies]
flu-core = { workspace = true }

[lints]
workspace = true
